
// Generated by https://quicktype.io

export interface BodyCuenta {
    version: string;
    header:  Header;
    payload: Payload[];
}

export interface Header {
    service:     string;
    institution: string;
    product:     string;
    user:        string;
}

export interface Payload {
    name:   string;
    format: Format;
    data:   Data;
}

export interface Data {
    value?:  string;
    values?: Array<string[] | string>;
}

export enum Format {
    Array = "array",
    String = "string",
}
